#!/usr/bin/env bash
#
# FF-IVY Cloud Agent install script (idempotent).
#
# Prepares a fully self-contained local dev stack so the app runs with no
# external services or secrets:
#   - local PostgreSQL 16 (system package)
#   - the app's Neon-over-HTTP driver talks to a local proxy (see start.sh)
#   - schema applied from db/migrations/*.sql
#   - .env.local generated with local dev credentials
#
# Safe to run repeatedly and before every Cloud Agent session.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
PROXY_DIR="$ROOT/.cursor/neon-proxy"
CERT_DIR="$PROXY_DIR/certs"

DB_USER="ivy"
DB_PASS="ivy_local_pw"
DB_NAME="ff_ivy"

echo "[install] Ensuring PostgreSQL is installed..."
if ! command -v pg_ctlcluster >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq postgresql postgresql-contrib
fi

echo "[install] Starting PostgreSQL cluster..."
sudo pg_ctlcluster 16 main start 2>/dev/null || true
for _ in $(seq 1 30); do
  if sudo -u postgres pg_isready -q 2>/dev/null; then break; fi
  sleep 1
done

echo "[install] Ensuring role '$DB_USER' and database '$DB_NAME' exist..."
if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='$DB_USER'" | grep -q 1; then
  sudo -u postgres psql -c "CREATE ROLE $DB_USER LOGIN PASSWORD '$DB_PASS'"
fi
if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" | grep -q 1; then
  sudo -u postgres createdb -O "$DB_USER" "$DB_NAME"
fi

echo "[install] Applying migrations..."
for f in "$ROOT"/db/migrations/*.sql; do
  echo "  - $(basename "$f")"
  PGPASSWORD="$DB_PASS" psql -h localhost -U "$DB_USER" -d "$DB_NAME" -v ON_ERROR_STOP=1 -q -f "$f"
done

# `npm install` (not `npm ci`): the committed lockfile omits some Linux-only
# optional deps, so `npm ci` refuses to run on this platform.
echo "[install] Installing app dependencies..."
npm install --no-audit --no-fund

echo "[install] Installing Neon proxy dependencies..."
( cd "$PROXY_DIR" && npm install --no-audit --no-fund )

echo "[install] Ensuring local TLS certificate for the Neon proxy..."
mkdir -p "$CERT_DIR"
if [ ! -f "$CERT_DIR/localhost-cert.pem" ] || [ ! -f "$CERT_DIR/localhost-key.pem" ]; then
  openssl req -x509 -newkey rsa:2048 -nodes \
    -keyout "$CERT_DIR/localhost-key.pem" -out "$CERT_DIR/localhost-cert.pem" \
    -days 3650 -subj "/CN=localhost" \
    -addext "subjectAltName=DNS:localhost,IP:127.0.0.1"
fi

echo "[install] Ensuring .env.local exists..."
if [ ! -f "$ROOT/.env.local" ]; then
  cat > "$ROOT/.env.local" <<EOF
# Generated by .cursor/install.sh for local Cloud Agent development.
# DATABASE_URL host is 'localhost' so @neondatabase/serverless fetches
# https://localhost/sql, served by the local Neon proxy (.cursor/neon-proxy).
DATABASE_URL=postgresql://$DB_USER:$DB_PASS@localhost:5432/$DB_NAME
APP_PASSWORD=ivy
SESSION_SECRET=$(openssl rand -hex 32)
MICROCLIMATE_WEBHOOK_SECRET=$(openssl rand -hex 24)
# Optional: set a real key to exercise natural-language voice intents.
OPENAI_API_KEY=
# Trust the proxy's self-signed cert for https://localhost/sql at node startup.
NODE_EXTRA_CA_CERTS=$CERT_DIR/localhost-cert.pem
EOF
fi

echo "[install] Done."
